project_name: steamid

# frontend is already output to dist, --clean will wipe it, so we use another location
dist: build

env_files:
  github_token: .github_releaser_token

builds:
  - id: steamid
    env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/leighmacdonald/steamid/steamid.BuildVersion={{.Version}} -X github.com/leighmacdonald/steamid/steamid.BuildCommit={{.Commit}} -X github.com/leighmacdonald/steamid/steamid.BuildDate={{.Date}}

nfpms:
  - maintainer: Leigh MacDonald <leigh.macdonald@gmail.com>
    description: Library and simple cli for steamid conversions
    homepage: https://github.com/leighmacdonald/steamid
    license: MIT
    formats:
      - deb
      - rpm
      - apk

archives:
  - builds:
      - steamid
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE.md
      - README.md
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

release:
  github:
    owner: leighmacdonald
    name: steamid
  draft: true
  replace_existing_draft: true
  prerelease: auto

changelog:
  use: github-native

#signs:
#  - artifacts: checksum
#    args:
#      - "--batch"
#      - "-u"
#      - "{{ .Env.GPG_FINGERPRINT }}"
#      - "--output"
#      - "${signature}"
#      - "--detach-sign"
#      - "${artifact}"

sboms:
  - artifacts: archive

# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
