name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2.5.1

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: make lin

    - name: Test
      run: make test
      env:
        STEAM_TOKEN: ${{ secrets.STEAM_TOKEN }}

    - name: Lint
      run: make lint
